name: FrancyMonoids
version: 0.1
date: 2018-06-04
description: |
    FrancyMonoids/A package to display commutative monoid objects with francy

authors:
    - name: Pedro A. García-Sánchez
      url: https://www.ugr.es/~pedro
    - name: Andrés Herrera-Poyatos
      url: https://github.com/andreshp
    - name: Manuel Martins
      url: http://github.com/mcmartins

maintainers:
    - name: Pedro A. García-Sánchez
      url: https://www.ugr.es/~pedro
    - name: Andrés Herrera-Poyatos
      url: https://github.com/andreshp
    - name: Manuel Martins
      url: http://github.com/mcmartins

GAP: "4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "francy"
      version: "0.6"
      url: "https://github.com/mcmartins/francy"
    - name: "NumericalSgps"
      version: "1.1.6"
      url: "https://gap-packages.github.io/numericalsgps"

www: https://gap-packages.github.io/francymonoids
readme: README.md
packageinfo: https://gap-packages.github.io/francymonoids/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/francymonoids/releases/download/v0.1/FrancyMonoids-0.1.tar.gz

abstract: |
    The <span class="pkgname">Example</span> package, provides some tools to draw objects related to affine and numerical semigroups.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    graphs commutative monoids, trees commutative monoids, trees commutative monoids.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>GHM18</span>]   <b class='BibAuthor'>García-Sánchez, P. A., Herrera-Poyatos, A. and Martins, M.</b>,
     <i class='BibTitle'>FrancyMonoids, FrancyMonoids/A package to display commutative monoid objects with francy,
             Version 0.1</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/francymonoids">https://gap-packages.github.io/francymonoids</a></span>.
    </p>
    

bibtex: |
    @misc{ FrancyMonoids0.1,
      author =           {Garc{\a'\i}a-S{\a'a}nchez,  P. A. and Herrera-Poyatos,
                          A. and Martins, M.},
      title =            {{FrancyMonoids},  FrancyMonoids/A  package  to display
                          commutative monoid objects with francy, {V}ersion 0.1},
      month =            {Jun},
      year =             {2018},
      note =             {GAP package},
      howpublished =     {\href   {https://gap-packages.github.io/francymonoids}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{francymonoids}}},
      keywords =         {graphs commutative monoids; trees commutative monoids;
                          trees commutative monoids},
      printedkey =       {GHM18}
    }

